### PR TITLE
Pre-MVP Release

### PR DESCRIPTION
**Pull request by DrPresident**

### CODE REVIEW

**Comment by mohammedpatla** [comment]
Hum this was also the reason i wanted to see if anything relevant should be done by me from https://github.com/securesecrets/shade/issues/28

**Review by mohammedpatla — APPROVED** [review]
This needs a code review, has everything until the restructuring of the code. Adding documentation if we are missing.

Also, any test if we missed it.

**Comment by DrPresident** [comment]
I can't approve it since I opened the PR

**Comment by mohammedpatla** [comment]
@FloppyDisck

**Comment by FloppyDisck** [comment]
I agree with @mohammedpatla , we should go over every single file in the PR and commend whatever we think is necessary to be updated before we continue

**Review by FloppyDisck — APPROVED** [review]

**Pull request merged**
