### PR TITLE
Secureprice

### PR DESCRIPTION
**Pull request by jaypersanchez**

### CODE REVIEW

**Comment by mohammedpatla** [comment]
@jaypersanchez in the future i would add lock files to gitignore.

**Comment by FloppyDisck** [comment]
There appear to be a few conflicts

**Comment by FloppyDisck** [comment]
Please move ./secure-secret over to ./contracts/oracle

Also try to connect your contract package to the root cargo file and add a reference to your contract there.

**Comment by mohammedpatla** [comment]
@jaypersanchez make sure to work on this pr branch so all your changes can be merged in once tested

**Comment by DrPresident** [comment]
Can we get rid of all the `Counter` related stuff?

**Comment by FloppyDisck** [comment]
Use the mint contract as a reference to how to structure the oracle contract

**Review by FloppyDisck — COMMENTED** [review]
you seem to have a folder containing a project inside the oracle dir, the oracle dir should be the project folder

**Pull request closed without merging**
