### PR TITLE
Snip initializer

### PR DESCRIPTION
**Pull request by FloppyDisck**
Created a new contract that initialized the Shade/Silk snip20s and stores the initial balances so the community can query them

### CODE REVIEW

**Comment by DrPresident** [comment]
This contracts function is already being handled by the deployment python scripts

**Comment by FloppyDisck** [comment]
@DrPresident yes but as per last meetings tasks, @mohammedpatla asked for a contract that deploys both snip20s and records their initial balances for public viewing

**Comment by mohammedpatla** [comment]
Ok as long as this initialized with balance for admin

**Review by mohammedpatla — APPROVED** [review]
As long as this is s version works with a drop on admin.

**Review by DrPresident — APPROVED** [review]

**Pull request merged**
